---
abstract: 'Export the current directory over HTTP'
author:
  - 'Pedro Melo <melo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-HTTPThis
requires:
  Getopt::Long: 0
  Net::Rendezvous::Publish: 0.04
  Plack::App::Directory: 0
  Plack::Runner: 0
  Pod::Usage: 0
resources:
  repository: http://github.com/melo/app-httpthis.git
version: 0.002
